[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xars"
version = "2.0.0"
description = "XARS simulates X-rays propagating through matter in user-defined geometries."
readme = "README.rst"
authors = [
    { name="Johannes Buchner", email="buchner.johannes@gmx.at" }
]
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Development Status :: 6 - Mature",
]
dependencies = [
    "numpy",
    "scipy",
    "tqdm",
    "matplotlib",
    "h5py",
]

[project.urls]
Homepage = "https://github.com/JohannesBuchner/xars"
Source = "https://github.com/JohannesBuchner/xars"
Documentation = "https://github.com/JohannesBuchner/xars"


[tool.setuptools]
packages = ["xars", "xars.geometries", "xars.binning", "xars.xsects"]

[tool.pytest.ini_options]
collect_ignore = "['setup.py', 'xars/xsects/xsects_convert.py']"
